-- PARA INSERIR DADOS EM UMA TABELA USAMOS:

INSERT INTO ExemploTabela (Coluna1, Coluna2, Coluna3)
VALUES ('Valor1', 'Valor2', 'Valor3'),
       ('OutroValor1', 'OutroValor2', 'OutroValor3');



-- COMO PODEMOS DELETAR LINHAS OU APENAS UMA LINHA DA NOSSA TABELA :

--DELETANDO TODAS AS LINHAS 
DELETE FROM NomeDaTabela;


--DELETANDO APENAS LINHAS QUE TEM A COLUNA COM UMA VALOR x

DELETE FROM NomeDaTabela
WHERE Coluna = 'x';


--PARA ALTERAR UM CAMPO DAMOS UM UPDATE NORMAL 