

--PODEMOS CRIAR UM DATABASE COMO O CÓDIGO A BAIXO OU PODEMOS CRIAR ATRAVÉS DE FERRAMENTAS DA IDE
CREATE DATABASE SUCOS_VENDAS_01
	ON(	name="SUCOS_VENDAS.DAT",
		FILENAME ="CAMINHO ONDE EU QUERO GUARDAR MEU BANCO",	
		SIZE = 10MB, -- POSSO DEFINIR O TAMANHO MINIMO DO MEU BANCO 
		MAXSIZE = 50MB,
		FILEGROWTH = 5MB
	)
	LOG ON(
		NAME = "SUCOS_VENDAS.LOG ",
		FILENAME ="CAMINHO ONDE EU QUERO GUARDAR MEU BANCO",	
		SIZE = 10MB, -- POSSO DEFINIR O TAMANHO MINIMO DO MEU BANCO 
		MAXSIZE = 50MB,
		FILEGROWTH = 5MB
	);


--PODEMOS APAGAR O DATABASE COM A IDE E TBM PODEMOS USAR O COMANDO ABAIXO
DROP DATABASE SUCOS_VENDAS_01;



-- SCRIPT PARA CRIAR UMA TABELA 
CREATE TABLE tb_clientes( --para criar uma tabela com um nome que contem espaço devemos colocar o nome entre []
	ID INT PRIMARY KEY, --DEVEMOS CONHECER OS TIPOS DE DADOS, PARA ISSO BASTA LER O ARQUIVO "TIPOS.TXT"
    CPF NVARCHAR(11),
	NOME VARCHAR(100),
	ENDERECO VARCHAR(150),
	DATA_NASCIMENTO DATE,
	SEXO CHAR(1),	
	CREDITO MONEY,
	ISALIVE BIT 
);

--COMANDO PARA DELETEAR UMA TABELA
DROP TABLE tb_clientes;


--PARA GERARMOS UMA COLUNA QUE É AUTOINCREMENTADA USAMOS A SINTAXE ABAIXO :

--COMANDO IDENTITY NO CAMPO QUE QUERMOS
CREATE TABLE Exemplo (
    ID INT PRIMARY KEY IDENTITY(1,1),  -- USANDO A SITAXE AO LADO O CAMPO IRÁ COMEÇAR A PARTIR DO NUMERO 1 E SERÁ INCREMENTADO DE 1 EM 1 PARA CADA NOVO REGISTRO
    Nome NVARCHAR(100)
);