CREATE TABLE PRODUTOS (
	ID VARCHAR PRIMARY KEY,
	DESCRICAO VARCHAR(100) NULL,
	SABOR VARCHAR(50) NULL,
	TAMANHO VARCHAR(50) NULL,
	EMBALAGEM VARCHAR(50) NULL,
	PRECO_LISTA FLOAT NULL
);

CREATE TABLE VENDEDORES(
	MATRICULA VARCHAR(5) PRIMARY KEY,
	NOME VARCHAR(100),
	BAIRRO VARCHAR(50),
	COMISSAO FLOAT,
	DATA_ADMISSAO DATE,
	FERIAS BIT
);


CREATE TABLE CLIENTES(
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(100),
	[ENDEREÇO] VARCHAR(150),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO VARCHAR(50),
	CEP VARCHAR(8),
	[DATA NASCIMENTO] DATE,
	IDADE INT,
	SEXO VARCHAR(1),
	[LIMITE DE CREDITO] FLOAT,
	[VOLUME COMPRA]FLOAT,
	[PRIMEIRA COMPRA] BIT,
);


CREATE TABLE VENDAS (
    NUMERO VARCHAR(5) PRIMARY KEY,
    [DATA] DATE,
    CPF VARCHAR(11),
    MATRICULA VARCHAR(5),
    IMPOSTO FLOAT,
    CONSTRAINT FK_CPF FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF), 
    CONSTRAINT FK_MATRICULA FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA) 
);



--PODEMOS VER OS DIGRAMAS 












